# These are supported funding model platforms

github: [fdhhhdjd]# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: user?u=65668237
open_collective: # Replace with a single Open Collective username
ko_fi: tientainguyen
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ["https://profile-forme.cf"]
facebook: ["https://www.facebook.com/people/Nguy%E1%BB%85n-Ti%E1%BA%BFn-T%C3%A0i/100006139249437/"]
